//the program generates a number between 0 and 100.
//the player has 5 chances to guess the number.
//on each chance, the program says if the chosen number is
//bigger or smaller than the number generated by the computer

import java.util.Random;
import java.util.Scanner;

public class Game {
    public static void main(String[] args) {
        int random = new Random().nextInt(100);
        Scanner reading = new Scanner(System.in);
        int pick;
        int count = 0;

        System.out.println(random);
        System.out.println("\n\n");

        while (count < 5) {
            pick = reading.nextInt();
            count++;

            if (pick == random) {
                System.out.println("Right answer! You win!");
                break;
            } else if (count == 5) {
                System.out.println("sorry, lets start again");
                break;
            } else if (pick > random) {
                System.out.println("try a smaller number");
            } else if (pick < random) {
                System.out.println("try a bigger number");
            }
        }

    }
}